name: Build CVP macOS

on:
  push:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build CVP macOS

    strategy:
      matrix:
        include:
          - arch: arm64
            runner: macos-14
            output: cvp-macos-arm64

          - arch: x64
            runner: macos-13
            output: cvp-macos-x64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OpenSSL
        run: |
          brew install openssl@3

      - name: Create bin directory
        run: |
          mkdir -p bin

      - name: Build
        run: |
          clang ./cliLINUX.c \
            -I"$(brew --prefix openssl@3)/include" \
            -L"$(brew --prefix openssl@3)/lib" \
            -lcrypto \
            -o "./bin/${{ matrix.output }}"

      - name: Check architecture
        run: |
          file "./bin/${{ matrix.output }}"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ./bin/${{ matrix.output }}
