build-macos:
  name: Build CVP macOS
  runs-on: macos-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build macOS ARM64
      run: |
        clang ./cliMACOS.c \
          -o ./bin/cvp-macos-arm64 \
          -lcrypto

    - name: Build macOS x86_64
      run: |
        clang ./cliMACOS.c \
          -arch x86_64 \
          -o ./bin/cvp-macos-x64 \
          -lcrypto

    - name: Upload macOS binaries
      uses: actions/upload-artifact@v4
      with:
        name: cvp-macos
        path: |
          bin/cvp-macos-arm64
          bin/cvp-macos-x64
